### ISSUE TITLE
Data read error

### ISSUE THREAD

**Issue by Li-mengjie** [nasunmit/scadbbb#2]
Hello, in fact, when I try to read the "ROSMAP.VascularCells.counts_full.rds" file using R (version 4.3.0 or 3.5), from the website http://compbio.mit.edu/scADbbb/, I always encounter the following error: "Error in readRDS("C:/Users/l1573/Desktop/ROSMAP.VascularCells.counts_full.rds"): error reading from connection." I have been unable to resolve this error, and I suspect it may be due to compatibility issues with the R version. However, I am very interested in this dataset, so I would like to ask if the author can share the 10X data in standard format with me. I would greatly appreciate it. My email is [1473257350@qq.com](mailto:1473257350@qq.com).

**Comment by nasunmit** [comment]
Hi,

Could you please check the size of the file you downloaded in your local computer and send it to me? I will double check if the file is fine.
Thank you!

Best,
Na
From: Li-mengjie ***@***.***>
Date: Monday, July 3, 2023 at 8:10 AM
To: nasunmit/scadbbb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nasunmit/scadbbb] 10X Data request (Issue #2)

Hello, in fact, when I try to read the "ROSMAP.VascularCells.counts_full.rds" file using R (version 4.3.0 or 3.5), from the website http://compbio.mit.edu/scADbbb/, I always encounter the following error: "Error in readRDS("C:/Users/l1573/Desktop/ROSMAP.VascularCells.counts_full.rds"): error reading from connection." I have been unable to resolve this error, and I suspect it may be due to compatibility issues with the R version. However, I am very interested in this dataset, so I would like to ask if the author can share the 10X data in standard format with me. I would greatly appreciate it. My email is ***@***.******@***.***>.

**Comment by Li-mengjie** [comment]
Hello, the size of the counts file I downloaded is 33,554,432 bytes，and I have downloaded it repeatedly.
<img width="304" alt="image" src="https://github.com/nasunmit/scadbbb/assets/99384654/719335e5-deb7-412b-b72f-7c30fcc7326a">
